name: Build
on: [push]

jobs:
  build:
    name: Run TestCafe Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 13.x    

      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run Tests
        env:
            PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        run: yarn percy exec -- testcafe chrome:headless src/test
      